### ISSUE TITLE
Question: is the mapping complete?

### ISSUE THREAD

**Issue by silkentrance** [sindresorhus/lcid#1]
I mean, are all available standard language codes part of the database or just the ones for which there is a windows equivalent?

**Comment by sindresorhus** [comment]
It's not complete, but there's no official documentation about it AFAIK (which is normal in the Microsoft world).

I've just borrowed the mappings from Python: https://github.com/python/cpython/blob/be2a1a76fa43bb1ea1b3577bb5bdd506a2e90e37/Lib/locale.py#L1395-L1604

Relevant comment:

```
# NOTE: this mapping is incomplete.  If your language is missing, please
# submit a bug report to the Python bug tracker at http://bugs.python.org/
# Make sure you include the missing language identifier and the suggested
# locale code.
```

**Comment by silkentrance** [comment]
@sindresorhus Thank you very much for the explanation.
