### ISSUE TITLE
Using `_` instead of `-` ?

### ISSUE THREAD

**Issue by yaf** [sindresorhus/lcid#2]
Hello,

Thanks for your work.

Why do you use `_` in your locale (ex: `en_US`) when RFC speak about hypen `-` (ex: `en-US`) ? 

https://tools.ietf.org/html/rfc4646#page-4

Thanks.

**Comment by sindresorhus** [comment]
I followed POSIX: https://en.wikipedia.org/wiki/Locale_(computer_software)

**Comment by yaf** [comment]
Thanks ! :-)
