### ISSUE TITLE
lcid depends on invert-kv@1.0.0, which is missing full license text

### ISSUE THREAD

**Issue by honzajavorek** [sindresorhus/lcid#3]
I'm sorry for bothering again (yes it's [me](https://github.com/sindresorhus/ama/issues/537) 😞 ), but I just discovered I cannot use `lcid` in my company, because it depends on `invert-kv@1.0.0`, which is missing a full license text in the distribution. `invert-kv@2` is fine, probably because it was published with a more recent version of the npm tool.

I noticed the version bump in `invert-kv` was done due to dropping a support for old Node versions. `lcid` still seems to support even node 0.10. Thus I think there are two solutions to that:

1. To just re-publish `invert-kv` as it is, with a recent npm version, which automatically includes the license file in the distribution. It could be released as `invert-kv@1.0.1` and as such it could propagate automatically, fixing any project depending on `^1.0.0`, including `lcid` (and anything depending on `lcid`, e.g. `yargs` or `nconf`).

2. To drop old node versions support here and upgrade `lcid` to use `invert-kv@^2`, but that would mean breaking change for `lcid` as well and wouldn't automatically propagate through the ecosystem.

I'm sorry again for being a PITA, but when the full text is missing, our lawyers consider the code unlicensed, thus fully copyrighted and unusable as open source.

**Comment by honzajavorek** [comment]
@sindresorhus You are amazing! 🙏 Would you mind propagating the version to https://github.com/sindresorhus/os-locale? I noticed that's the project through which it gets to both `nconf` and `yargs`... and it's yours as well 😅

**Comment by sindresorhus** [comment]
Done
