### ISSUE TITLE
Issues with the Spanish locale

### ISSUE THREAD

**Issue by mwanago** [sindresorhus/lcid#7]
Hello
I'm experiencing issues with the Spanish locale.
In the [mappings](https://github.com/python/cpython/blob/be2a1a76fa43bb1ea1b3577bb5bdd506a2e90e37/Lib/locale.py#L1395-L1604), there are two different codes for Spanish:
```
0x040a: "es_ES", # Spanish - Spain
0x0c0a: "es_ES", # Spanish - Spain (Modern)
```
The first one unfortunately doesn't work when calling the `from` method.
```
from(1034); // undefined
```

**Comment by sindresorhus** [comment]
I must have missed that one when adopting the Python mapping. The current code in the package here doesn't account for there being multiple codes with the same label either, so it will need some refactoring.

**Comment by mwanago** [comment]
I will create a PR

**Comment by mwanago** [comment]
@sindresorhus Any news on the review of that PR? Cheers :)
